spring:
  data:
    mongodb:
      database: employee
      port: 27017
      host: localhost
      auto-index-creation: true
      uri: mongodb+srv://raresamza01:zugravul70@employee.apjtxke.mongodb.net/?retryWrites=true&w=majority



